"""Emit a temp ``arguments/multipleview/<name>.py``-style bridge file from a resolved
``PipelineConfig`` — how T09's CUDA stages hand ``ModelHiddenParams``/``OptimizationParams``/
``ModelParams``/``PipelineParams`` to the vendored, argparse-based reference scripts
(``pipeline/vendored/cuda/{train,render,seg_extract,amp}.py``) without CLI-flag gymnastics.

Why this exists: ``arguments/__init__.py``'s ``ParamGroup`` builds one ``--flag`` per field, but
that mechanism can't round-trip every field type CLI-side — ``ModelHiddenParams.kplanes_config``
is a nested dict and ``.multires`` is a list, neither of which ``ParamGroup``'s naive
``type=type(default_value)`` argparse wiring can parse back from a string. The reference
pipeline's own answer to this (``train_pump.sh``'s ``--configs arguments/multipleview/pump01.py``)
is a plain Python file assigning ``ModelHiddenParams``/``OptimizationParams`` dict literals, loaded
via ``mmengine.Config.fromfile`` and merged over CLI args by ``utils/params_utils.merge_hparams``
— which also (see its ``params`` list) merges ``ModelParams``/``PipelineParams`` dict keys the
same way. This module writes exactly that file, generated from the resolved config instead of
hand-authored, so config stays the single source of truth (``planning/INSTRUCTIONS.md``) even for
fields the CLI mechanism can't carry.

``source_path``/``model_path`` are deliberately **excluded** from the emitted ``ModelParams``
dict: T09's stages derive these from the DAG's own artifact wiring (this run's ``scene``/``model``
artifact paths, translated to the container's view) and pass them as explicit CLI flags — see
``pipeline.config.models.ModelParams``'s docstring ("normally *derived* ... until that wiring
lands" — this module is that wiring). Since ``merge_hparams`` applies unconditionally
(``setattr(args, key, value)`` for every key present in a merged group, regardless of what the
CLI passed), leaving them in the bridge file would silently override the CLI values with
whatever the *config* happens to say (empty string, by default) — excluding them is what makes
the CLI-passed values actually stick.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

#: the four dict literals `utils/params_utils.merge_hparams` looks for, in the same order
#: `arguments/multipleview/*.py` files conventionally use.
_BRIDGE_GROUPS: tuple[tuple[str, str], ...] = (
    ("model", "ModelParams"),
    ("pipeline_params", "PipelineParams"),
    ("hidden", "ModelHiddenParams"),
    ("optim", "OptimizationParams"),
)

#: `ModelParams` fields intentionally left out of the bridge file — see module docstring.
_MODEL_FIELDS_EXCLUDED_FROM_BRIDGE = ("source_path", "model_path")

_HEADER = (
    "# Auto-generated by pipeline.config.bridge for one pipeline run — do not hand-edit.\n"
    "# Edit the originating preset instead (pipeline/config/presets/*.yaml) and re-run.\n"
)


def render_bridge_source(resolved_config: dict[str, Any]) -> str:
    """Build the bridge file's *text* from a resolved ``PipelineConfig`` dict (``model_dump()``).

    Pure/side-effect-free (no filesystem access) so it's independently testable; :func:`write_
    bridge` is the thin wrapper that actually writes it to a run-scoped path.
    """
    lines = [_HEADER]
    for section_key, group_name in _BRIDGE_GROUPS:
        section = dict(resolved_config[section_key])
        if section_key == "model":
            for field in _MODEL_FIELDS_EXCLUDED_FROM_BRIDGE:
                section.pop(field, None)
        # `repr()` of a plain dict of JSON-safe values (str/int/float/bool/None/list/dict) is
        # always a valid Python literal that round-trips via `runpy`/`mmengine.Config.fromfile`
        # — the same trust model `pipeline.config.loader.load_legacy_hyperparams` already uses
        # for these files (see its module docstring).
        lines.append(f"{group_name} = {section!r}\n")
    return "".join(lines)


def write_bridge(resolved_config: dict[str, Any], out_path: str | Path) -> Path:
    """Write :func:`render_bridge_source`'s output to ``out_path`` (creating parent dirs) and
    return it as a :class:`~pathlib.Path`. ``out_path`` is a *host* path — translate to the
    container's view yourself (``ctx.paths.to_container(...)``) before passing it as a stage's
    ``--configs`` CLI value.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_bridge_source(resolved_config))
    return out_path
